plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.olyposecamera'
version = '0.1.0'

android {
  namespace 'expo.modules.olyposecamera'
  defaultConfig {
    versionCode 1
    versionName '0.1.0'
  }
  sourceSets.main.assets.srcDirs = ['../assets']
}

dependencies {
  implementation 'com.google.mediapipe:tasks-vision:0.10.29'
  implementation 'androidx.camera:camera-camera2:1.4.2'
  implementation 'androidx.camera:camera-lifecycle:1.4.2'
  implementation 'androidx.camera:camera-view:1.4.2'
}
