plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

group = 'expo.modules.mediapipepose'
version = new groovy.json.JsonSlurper().parse(file('../package.json')).version

android {
  namespace 'expo.modules.mediapipepose'
  defaultConfig {
    versionCode 1
    versionName project.version.toString()
  }
  sourceSets.main.assets.srcDirs = ['../assets']
}

dependencies {
  testImplementation 'junit:junit:4.13.2'
  implementation 'androidx.exifinterface:exifinterface:1.4.2'
  implementation 'com.google.mediapipe:tasks-vision:0.10.29'
  implementation 'androidx.camera:camera-camera2:1.4.2'
  implementation 'androidx.camera:camera-lifecycle:1.4.2'
  implementation 'androidx.camera:camera-view:1.4.2'
}
